ba_2motifs:
  groundtruth: "True"
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 300
  lr: 0.001
  weight_decay: 0.0000
  dropout: 0.0
  readout: "max"
  batch_size: 200
  unseen: "False"
  
ba_house_grid:
  num_graphs: 2000
  num_shapes: 5
  width_basis: 80
  groundtruth: "True"
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 300
  lr: 0.001
  weight_decay: 0.0000
  dropout: 0.0
  readout: "max"
  batch_size: 200
  unseen: "False"

ba_multishapes:
  groundtruth: "True"
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 300
  lr: 0.001
  weight_decay: 0.0000
  dropout: 0.0
  readout: "max"
  batch_size: 200
  unseen: "False"

common_params: &common_params
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 32
  num_epochs: 200
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.0
  readout: "max"
  batch_size: 64
  gamma: 0.5
  milestones: [70, 90, 120, 170]
  num_early_stop: 50
  unseen: "False"

mutag:
  <<: *common_params
  groundtruth: "True"
  explained_target: 0

benzene:
  <<: *common_params
  groundtruth: "True"
  explained_target: 1

mnist:
  <<: *common_params
  groundtruth: "True"

mnist_bin:
  <<: *common_params
  groundtruth: "True"

graphsst2:
  <<: *common_params
  groundtruth: "False"

mutag_s:
  <<: *common_params
  groundtruth: "False"
  explained_target: 1

bbbp:
  <<: *common_params
  groundtruth: "False"
  explained_target: 1

common_params_powergrid: &common_params_powergrid
  groundtruth: "True"
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 32
  num_epochs: 200
  lr: 0.001
  weight_decay: 0.0
  dropout: 0.0
  readout: "cat_max_sum"
  batch_size: 128
  gamma: 0.5
  milestones: [70, 90, 120, 170]
  num_early_stop: 50
  unseen: "False"

uk_mc:
  <<: *common_params_powergrid

ieee24_mc:
  <<: *common_params_powergrid

ieee24_bin:
  <<: *common_params_powergrid

ieee39_mc:
  <<: *common_params_powergrid

ieee118_mc:
  <<: *common_params_powergrid

common_params_syn: &common_params_syn
  groundtruth: "True"
  graph_classification: "False"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 1000
  lr: 0.001
  weight_decay: 0.005
  dropout: 0.0
  readout: "identity"
  unseen: "False"

ba_house:
  <<: *common_params_syn

ba_bottle:
  <<: *common_params_syn

tree_grid:
  <<: *common_params_syn

tree_cycle:
  <<: *common_params_syn

ba_grid:
  <<: *common_params_syn

ba_community:
  <<: *common_params_syn

common_params_citation: &common_params_citation
  groundtruth: "False"
  graph_classification: "False"
  num_layers: 2
  hidden_dim: 16
  num_epochs: 200
  lr: 0.01
  weight_decay: 0.0005
  dropout: 0.5
  readout: "identity"
  unseen: "False"

cora:
  <<: *common_params_citation

citeseer:
  <<: *common_params_citation

pubmed:
  <<: *common_params_citation
